name: Deploy Admin Panel Client to Test Env

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'git-tag'
        required: true
      previous_tag:
        description: 'previous-release'
        required: true

env:
  project-directory: ./

jobs:
  build:
    name: Build Client Project
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, 'skip-ci')
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: npm clean install
        run: npm ci
        working-directory: ${{ env.project-directory }}
      - name: build client project
        run: CI= REACT_APP_WEBMAP_DOMAIN=http://test.treetracker.org REACT_APP_API_ROOT=https://test-k8s.treetracker.org/api/admin npm run build
        working-directory: ${{ env.project-directory }}
      - uses: actions/upload-artifact@v2
        with:
          name: client-bundle
          path: build

  deploy:
    name: Deploy to CDN
    runs-on: ubuntu-latest
    needs: build
    if: |
      github.repository == 'Greenstand/treetracker-admin-client'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Download bundled client resources
        uses: actions/download-artifact@v2
        with:
          name: client-bundle
          path: build
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-east-1
      - name: Copy front end resources to s3 bucket
        run: |
          aws s3 sync build s3://${{ secrets.TEST_CDN_S3_BUCKET }} --delete
      - name: Invalidate cloudfront caches
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.TEST_CDN_DISTRIBUTION_ID }} --paths "/*"

  changelog:
    name: Build Changelog
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: Generate Changelog
      id: generate_changelog
      uses: mikepenz/release-changelog-builder-action@v2.5.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        fromTag: ${{ github.event.inputs.previous_tag }}
        toTag: ${{ github.event.inputs.tag }}
    - name: Notify Slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"D013589M8P8\",\"text\":\"${{steps.generate_changelog.outputs.changelog}}\"}'
