# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Admin Panel Client CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  project-directory: ./

jobs:
  client:
    name: Build Client Project
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, 'skip-ci')
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm clean install
        run: npm ci
        working-directory: ${{ env.project-directory }}
      - name: run ESLint
        run: npm run lint
        working-directory: ${{ env.project-directory }}
      - name: build client dev project
        if: github.event_name == 'push' && github.repository == 'Greenstand/treetracker-admin-client'
        run: npm run build:dev
        working-directory: ${{ env.project-directory }}
      - uses: actions/upload-artifact@v2
        if: github.event_name == 'push' && github.repository == 'Greenstand/treetracker-admin-client'
        with:
          name: client-bundle
          path: build-dev
      - name: build client project
        run: npm run build
        working-directory: ${{ env.project-directory }}
      - name: run React tests
        run: npm test
        working-directory: ${{ env.project-directory }}
  release:
    name: Release semantic version
    needs: client
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, 'skip-ci') &&
      github.event_name == 'push' &&
      github.repository == 'Greenstand/treetracker-admin-client'
    steps:
      # check out repository code and setup node
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      # install dependencies and run semantic-release
      - run: npm i -g semantic-release @semantic-release/{git,exec,changelog}
      - run: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    name: Deploy to dev CDN
    runs-on: ubuntu-latest
    needs: release
    if: |
      !contains(github.event.head_commit.message, 'skip-ci') &&
      github.event_name == 'push' &&
      github.repository == 'Greenstand/treetracker-admin-client'
    steps:
      - uses: actions/checkout@v2
      - name: Download bundled client resources
        uses: actions/download-artifact@v2
        with:
          name: client-bundle
          path: build-dev
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-east-1
      - name: Copy front end resources to s3 bucket
        run: |
          aws s3 sync build-dev s3://${{ secrets.DEV_CDN_S3_BUCKET }} --delete
      - name: Invalidate cloudfront caches
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.DEV_CDN_DISTRIBUTION_ID }} --paths "/*"
